#! /bin/bash

set -e

# These are passed on to post-bootstrap.sh
export DOTFILES_REPO="Mossop/dotfiles"
export DOTFILES_BRANCH="master"
export DOTFILES="$HOME/dotfiles"

if [ -d "$DOTFILES" ]; then
  echo "$DOTFILES already exists."
  exit 0
fi

if command -v git 1>/dev/null 2>&1; then
  git clone -q -b $DOTFILES_BRANCH "https://github.com/${DOTFILES_REPO}.git" "$DOTFILES"
else
  echo "Git is not installed. Falling back to an archive install."

  if ! command -v tar 1>/dev/null 2>&1; then
    echo "tar is not installed, cannot proceed."
    exit 1
  fi

  if command -v curl 1>/dev/null 2>&1; then
    mkdir -p "$DOTFILES"
    curl -sL "https://github.com/${DOTFILES_REPO}/archive/${DOTFILES_BRANCH}.tar.gz" | tar -xpz -C "$DOTFILES" --strip-components=1
  elif command -v wget 1>/dev/null 2>&1; then
    mkdir -p "$DOTFILES"
    wget --quiet -O - "https://github.com/${DOTFILES_REPO}/archive/${DOTFILES_BRANCH}.tar.gz" | tar -xpz -C "$DOTFILES" --strip-components=1
  else
    echo "Neither curl nor wget are available, cannot proceed."
    exit 1
  fi
fi

exec "$DOTFILES/scripts/post-bootstrap.sh"
