#! /bin/bash

set -e

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]:-$0}") && pwd | sed -e s/\\/$//g)

. "$DOTFILES/includes/functions.sh"
. "$DOTFILES/includes/config.sh"

echo "Installing..."

#
# Install the startup script.
#
GREPTERM="dotfiles-init"

if [ ! -f "$HOME/.profile" ]; then
  touch "$HOME/.profile"
else
  sed -i.bak "/$GREPTERM/d" "$HOME/.profile"
  rm -f "$HOME/.profile.bak"
fi

if [ ! -f "$HOME/.bashrc" ]; then
  touch "$HOME/.bashrc"
else
  sed -i.bak "/$GREPTERM/d" "$HOME/.bashrc"
  rm -f "$HOME/.bashrc.bak"
fi

echo "source \"$DOTFILES/scripts/startup.sh\" # $GREPTERM" >> "$HOME/.profile"
echo "source \"$DOTFILES/scripts/startup.sh\" # $GREPTERM" >> "$HOME/.bashrc"

install_files "$DOTFILES/home" "$HOME"
install_files "$PLATFORM_DIR/home" "$HOME"

update_git_repo "$DOTFILES/external/pyenv"
update_git_repo "$DOTFILES/external/pyenv/plugins/pyenv-virtualenv"

maybe_source "$PLATFORM_DIR/install.sh"
