#! /bin/sh

set -e

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]:-$0}") && cd .. && pwd | sed -e s/\\/$//g)

. "$DOTFILES/includes/functions.sh"
. "$DOTFILES/includes/config.sh"

pull_git_repo "https://github.com/pyenv/pyenv.git" "$DOTFILES/external/pyenv"
