[user]
name = "Dave Townsend"
email = "dtownsend@oxymoronical.com"

#[core]
#fsmonitor = "watchman"

[colors]
"diff token" = { underline = false }

[diff.git]
context = 8

[diff.color-words]
context = 8

[ui]
merge-editor = "vscode"
pager = "less -FRX"
diff.format = "git"
diff-editor = "meld"

[aliases]
br = ["util", "exec", "--", "jj-bookmark-rebase"]

[revset-aliases]
"branch()" = "branch(@)"
"branch(x)" = "(::x | x::) & mutable()"
"base()" = "base(@)"
"base(x)" = "roots(::x & mutable())"
"branch_point()" = "branch_point(@)"
"branch_point(x)" = "heads(::x & immutable())"

[experimental-advance-branches]
enabled-branches = ["glob:*"]

[git]
subprocess = true
