--when.repositories = [
  "~/mozilla-source/source",
  "~/mozilla/source",
  "E:/mozilla-source/source",
  "F:/mozilla-source/source",
]

[git]
fetch = ["firefox", "enterprise"]
push = "firefox"

[remotes.firefox]
auto-track-bookmarks = "glob:'work/*'"

[remotes.enterprise]
auto-track-bookmarks = "glob:'enterprise/*'"

[aliases]
closed = ["util", "exec", "--", "bash", "-c", """
jj abandon -r "subject(regex-i:\\"^bug $1\\\\\\b\\") & mine() & mutable()"
""", ""]

[revset-aliases]
"bug(x)" = 'subject(regex-i:"^bug \\d{0,7}\\b") & subject(substring:x)'
"wip(x)" = "bug(x) & mine() & mutable()"
"trunk()" = "main@firefox"
